#!/usr/bin/env node
/**
 * PR Comment Reporter
 *
 * Reads a scan-results.json file and outputs a Markdown summary
 * suitable for posting as a GitHub PR comment.
 *
 * Usage: node dist/pr-comment.js <scan-results.json>
 */

import fs from "node:fs";
import type { Finding, ScanResult, Severity } from "../core/scan.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🔵"
};

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];
const MAX_FINDINGS_PER_SEVERITY = 10;

function loadResults(filePath: string): ScanResult {
    const raw = fs.readFileSync(filePath, "utf8").trim();
    if (!raw || raw === "No findings.") {
        return { findings: [] };
    }
    try {
        return JSON.parse(raw) as ScanResult;
    } catch {
        return { findings: [] };
    }
}

function groupBySeverity(findings: Finding[]): Record<Severity, Finding[]> {
    const groups: Record<Severity, Finding[]> = {
        critical: [],
        high: [],
        medium: [],
        low: []
    };
    for (const f of findings) {
        groups[f.severity]?.push(f);
    }
    return groups;
}

function renderSummaryTable(groups: Record<Severity, Finding[]>): string {
    const lines: string[] = [];
    lines.push("| Severity | Count |");
    lines.push("|----------|-------|");
    for (const sev of SEVERITY_ORDER) {
        const count = groups[sev].length;
        if (count > 0) {
            lines.push(`| ${SEVERITY_EMOJI[sev]} ${sev.toUpperCase()} | ${count} |`);
        }
    }
    return lines.join("\n");
}

function renderFindingRow(f: Finding): string {
    const location = f.line ? `\`${f.file}:${f.line}\`` : `\`${f.file}\``;
    const owasp = f.owasp ? ` — ${f.owasp}` : "";
    const pkg = f.category === "dependency" && f.packageName
        ? ` 📦 \`${f.packageName}${f.packageVersion ? `@${f.packageVersion}` : ""}\``
        : "";
    const rec = f.recommendation ? `\n    > 💡 ${f.recommendation}` : "";
    return `- **${f.title}** (${location})${owasp}${pkg}\n  ${f.description}${rec}`;
}

function renderMarkdown(result: ScanResult): string {
    const lines: string[] = [];
    const total = result.findings.length;

    lines.push("## 🔒 OpenSecurity Scan Results");
    lines.push("");

    if (total === 0) {
        lines.push("✅ **No security findings detected.** Great job!");
        return lines.join("\n");
    }

    const groups = groupBySeverity(result.findings);
    const criticalCount = groups.critical.length + groups.high.length;

    if (criticalCount > 0) {
        lines.push(`> ⚠️ **${criticalCount} critical/high severity issue${criticalCount > 1 ? "s" : ""} found.** Please review before merging.`);
    } else {
        lines.push(`> ℹ️ **${total} finding${total > 1 ? "s" : ""} detected.** No critical issues.`);
    }

    lines.push("");
    lines.push("### Summary");
    lines.push("");
    lines.push(renderSummaryTable(groups));
    lines.push("");

    for (const sev of SEVERITY_ORDER) {
        const items = groups[sev];
        if (items.length === 0) continue;

        lines.push(`### ${SEVERITY_EMOJI[sev]} ${sev.toUpperCase()} (${items.length})`);
        lines.push("");

        const shown = items.slice(0, MAX_FINDINGS_PER_SEVERITY);
        for (const f of shown) {
            lines.push(renderFindingRow(f));
        }

        if (items.length > MAX_FINDINGS_PER_SEVERITY) {
            const remaining = items.length - MAX_FINDINGS_PER_SEVERITY;
            lines.push(`\n<details><summary>…and ${remaining} more ${sev} finding${remaining > 1 ? "s" : ""}</summary>\n`);
            for (const f of items.slice(MAX_FINDINGS_PER_SEVERITY)) {
                lines.push(renderFindingRow(f));
            }
            lines.push("\n</details>");
        }

        lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by [OpenSecurity](https://github.com/opensecurity) 🛡️*");

    return lines.join("\n");
}

// --- Main ---

const args = process.argv.slice(2);
const inputFile = args[0];

if (!inputFile) {
    console.error("Usage: node pr-comment.js <scan-results.json>");
    process.exit(1);
}

const result = loadResults(inputFile);
console.log(renderMarkdown(result));
